### ISSUE TITLE
Uploaded file - Internal Server Error - probably unicode?

### ISSUE THREAD

**Issue by kanarinka** [mitmedialab/DataBasic#208]
Here's the sample data causing the bug: https://www.dropbox.com/s/vhnx2zkf1913c7w/CAUSES_INTERNAL_SERVER_ERROR.xls?dl=0

**Comment by kanarinka** [comment]
Note - this file works when converted to .csv

**Comment by jayvachon** [comment]
I don't know if we're supporting .xls? only .xlsx if I remember right

**Comment by kanarinka** [comment]
Ah ok - we should make it fail more nicely then...

**Comment by jayvachon** [comment]
for sure. but actually now I'm remembering that there should be form validation for file types so I'm not 100% sure about my previous comment

**Comment by jpailthorpe** [comment]
@kanarinka is this still active?
